// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconCommunity: typeof import('./../src/components/icons/IconCommunity.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleBar: typeof import('./../src/components/TitleBar/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
  }
}

export {}
